/* ===== Biblioteca de ejercicios de gimnasio =====
   Cada ejercicio: patrón de movimiento, músculo principal y secundarios, material necesario (req),
   exigencia articular (h hombro · c codo · m muñeca · l lumbar · r rodilla · k cadera; 1 moderada, 2 alta),
   flags: C compuesto · S énfasis en posición estirada · B apto para empezar,
   rep: f 6-10 · h 8-12 · a 10-15 · r 12-20 · s segundos. */
const MUSCLES={pecho:"Pecho",hombro_ant:"Hombro anterior",hombro_lat:"Hombro lateral",hombro_post:"Hombro posterior",dorsal:"Dorsal",espalda_media:"Espalda media",trapecio:"Trapecio",biceps:"Bíceps",triceps:"Tríceps",cuadriceps:"Cuádriceps",isquios:"Isquiotibiales",gluteo:"Glúteo",aductores:"Aductores",gemelo:"Gemelo",abdomen:"Abdomen",lumbar:"Lumbar"};
const PATTERNS={
  empuje_h:"Empuje horizontal",aperturas:"Aperturas de pecho",empuje_v:"Empuje vertical",elev_lateral:"Elevaciones laterales",deltoide_post:"Hombro posterior",
  tiron_v:"Tirón vertical",tiron_h:"Tirón horizontal",pullover:"Pullover",trapecio:"Trapecio",biceps:"Bíceps",triceps:"Tríceps",
  sentadilla:"Sentadilla y prensa",zancada:"Unilateral de pierna",ext_rodilla:"Extensión de rodilla",bisagra:"Bisagra de cadera",flex_rodilla:"Curl femoral",
  gluteo:"Glúteo",aductor:"Aductores",gemelo:"Gemelo",core:"Abdomen y core"
};
const JOINTS={h:"Hombro",c:"Codo",m:"Muñeca",l:"Lumbar",r:"Rodilla",k:"Cadera"};
const REPS={f:[6,10],h:[8,12],a:[10,15],r:[12,20],s:[30,60]};
const REST={f:150,h:120,a:75,r:60,s:60};

/* Material del gimnasio. kind: base (general) o maquina */
const GYM_ITEMS=[
  ["barra","Barra y discos","base"],["rack","Jaula o rack de sentadilla","base"],["banco","Banco plano","base"],["banco_inc","Banco inclinable","base"],
  ["mancuernas","Mancuernas","base"],["smith","Multipower (Smith)","base"],["poleas","Poleas / cruce de poleas","base"],["barra_dominadas","Barra de dominadas","base"],
  ["paralelas","Paralelas para fondos","base"],["kettlebell","Kettlebells","base"],["banco_45","Banco de hiperextensiones 45°","base"],["trap","Barra hexagonal","base"],["banco_scott","Banco Scott (predicador)","base"],
  ["prensa","Prensa inclinada 45°","maquina"],["prensa_h","Prensa horizontal","maquina"],["hack","Sentadilla hack","maquina"],["pendulo","Sentadilla péndulo","maquina"],
  ["ext_cuad","Extensión de cuádriceps","maquina"],["curl_fem_sentado","Curl femoral sentado","maquina"],["curl_fem_tumbado","Curl femoral tumbado","maquina"],
  ["aductor","Aductores","maquina"],["abductor","Abductores","maquina"],["hip_thrust_maq","Hip thrust de máquina","maquina"],
  ["gemelo_pie","Gemelo de pie","maquina"],["gemelo_sentado","Gemelo sentado","maquina"],
  ["press_pecho","Press de pecho","maquina"],["press_pecho_inc","Press de pecho inclinado","maquina"],["contractora","Contractora (pec deck)","maquina"],
  ["press_hombro","Press de hombro","maquina"],["elev_lat_maq","Elevaciones laterales","maquina"],
  ["jalon","Jalón al pecho","maquina"],["remo_maq","Remo con apoyo de pecho","maquina"],["pullover_maq","Pullover","maquina"],
  ["curl_maq","Curl de bíceps","maquina"],["triceps_maq","Tríceps / fondos sentado","maquina"],["asistida","Dominadas y fondos asistidos","maquina"]
];
const GYM_ITEM=Object.fromEntries(GYM_ITEMS.map(([id,t,k])=>[id,{id,t,k}]));
const GYM_DEFAULT_OFF=["pendulo","trap","banco_scott","elev_lat_maq","hip_thrust_maq","pullover_maq"];

const EX=[];
function X(id,name,pat,prim,sec,req,stress,flags,rep,cues,err,inc){
  const st={};(stress||"").split(" ").filter(Boolean).forEach(s=>{st[s[0]]=+s[1];});
  EX.push({id,name,pat,prim,sec:sec?sec.split(" "):[],req:req.split(" "),st,C:flags.includes("C"),S:flags.includes("S"),B:flags.includes("B"),rep,cues:cues.split("|"),err,inc:inc||null});
}
/* ---- Pecho ---- */
X("press_banca","Press banca con barra","empuje_h","pecho","triceps hombro_ant","barra banco","h2 c1 m1","C","f","Junta y baja las escápulas antes de descolgar|Baja la barra a la parte baja del pecho con los codos a unos 45-60°|Pies firmes en el suelo; empuja con todo el cuerpo","Rebotar la barra en el pecho o despegar los glúteos del banco",2.5);
X("press_banca_inclinado","Press inclinado con barra","empuje_h","pecho","hombro_ant triceps","barra banco_inc","h2 c1 m1","C","f","Banco a 30°, no más: a más ángulo trabaja más el hombro|Baja la barra a la parte alta del pecho|Escápulas atrás durante todo el recorrido","Arquear tanto la espalda que el ejercicio se convierte en press plano",2.5);
X("press_mancuernas","Press plano con mancuernas","empuje_h","pecho","triceps hombro_ant","mancuernas banco","h1 c1","CS","h","Baja hasta notar estiramiento en el pecho, sin dolor en el hombro|Muñecas encima de los codos|Sube juntando ligeramente las mancuernas","Acortar el recorrido para mover más peso",2);
X("press_mancuernas_inclinado","Press inclinado con mancuernas","empuje_h","pecho","hombro_ant triceps","mancuernas banco_inc","h1 c1","CS","h","Banco a 30°|Baja controlando 2-3 segundos|Codos ligeramente por delante del cuerpo, no abiertos en cruz","Dejar caer las mancuernas al final y perder la tensión",2);
X("press_smith_inclinado","Press inclinado en multipower","empuje_h","pecho","hombro_ant triceps","smith banco_inc","h1 c1","CSB","h","Coloca el banco para que la barra caiga en la parte alta del pecho|Escápulas atrás y abajo|Recorrido completo y controlado","Banco mal colocado: la barra baja al cuello o al abdomen",2.5);
X("press_smith_plano","Press plano en multipower","empuje_h","pecho","triceps hombro_ant","smith banco","h1 c1","CB","h","La barra debe bajar a la parte baja del pecho|Codos a unos 45-60°|Sin bloquear de golpe arriba","Bajar la barra demasiado alta, hacia el cuello",2.5);
X("press_pecho_maquina","Press de pecho en máquina","empuje_h","pecho","triceps hombro_ant","press_pecho","h1","CSB","h","Ajusta el asiento para que las asas queden a la altura del pecho medio|Espalda pegada al respaldo|Deja que las asas vuelvan hasta notar estiramiento","Asiento demasiado alto: el hombro hace el trabajo",2.5);
X("press_pecho_inclinado_maquina","Press inclinado en máquina","empuje_h","pecho","hombro_ant triceps","press_pecho_inc","h1","CSB","h","Asiento a la altura que las asas salgan de la parte alta del pecho|Empuja sin despegar los hombros del respaldo|Vuelta lenta","Encoger los hombros al empujar",2.5);
X("press_pecho_unilateral_inclinado","Press inclinado unilateral en máquina","empuje_h","pecho","hombro_ant triceps","press_pecho_inc","h1","CSB","h","Un brazo cada vez: mejor recorrido y menos compensaciones|Mano libre en el pecho para notar el músculo|Mismas repeticiones en ambos lados","Girar el tronco para ayudarte",2.5);
X("fondos","Fondos en paralelas","empuje_h","pecho","triceps hombro_ant","paralelas","h2 c1","CS","h","Inclínate un poco adelante para cargar más el pecho|Baja hasta que el hombro quede a la altura del codo, sin forzar|Hombros lejos de las orejas","Bajar demasiado con el hombro adelantado",2.5);
X("fondos_asistidos","Fondos asistidos en máquina","empuje_h","pecho","triceps","asistida","h2 c1","CSB","h","Más contrapeso es más ayuda|Inclínate ligeramente adelante|Baja controlando","Bloquear los codos de golpe",5);
X("flexiones","Flexiones","empuje_h","pecho","triceps hombro_ant abdomen","","h1 m1","CB","r","Cuerpo en bloque: glúteo y abdomen apretados|Manos algo más abiertas que los hombros|Pecho casi al suelo","Dejar caer la cadera",0);
X("flexiones_deficit","Flexiones en déficit","empuje_h","pecho","triceps hombro_ant","","h1 m1","CS","r","Manos sobre dos discos o agarres para bajar más|Baja hasta notar estiramiento|Mismo bloque que la flexión normal","Perder la línea del cuerpo al fatigarte",0);
X("press_suelo_mancuernas","Press en el suelo con mancuernas","empuje_h","pecho","triceps","mancuernas","c1","CB","h","Tumbado en el suelo: el recorrido para cuando el codo toca|Codos a 45°|Muy amable con el hombro","Rebotar los codos contra el suelo",2);
X("press_polea_pie","Press de pecho en polea de pie","empuje_h","pecho","triceps hombro_ant","poleas","h1","CB","a","Un pie adelantado para estabilizar|Empuja juntando las manos delante|Vuelve hasta notar estiramiento","Arquear la zona lumbar",2.5);
X("aperturas_mancuernas","Aperturas con mancuernas","aperturas","pecho","hombro_ant","mancuernas banco","h1","S","a","Codos ligeramente flexionados y fijos|Abre hasta notar estiramiento, no más|Cierra como si abrazaras un árbol","Convertirlo en un press doblando los codos",2);
X("contractora","Contractora (pec deck)","aperturas","pecho","hombro_ant","contractora","h1","SB","a","Asiento con las asas a la altura del pecho|Codos algo flexionados|Pausa breve con las manos juntas","Dejar que las asas se vayan muy atrás de golpe",2.5);
X("cruce_poleas","Cruce de poleas de arriba abajo","aperturas","pecho","hombro_ant","poleas","h1","SB","a","Poleas altas, un paso adelante|Junta las manos a la altura del ombligo|Estira abriendo los brazos con control","Mover el tronco en cada repetición",2.5);
X("cruce_poleas_bajo","Cruce de poleas de abajo arriba","aperturas","pecho","hombro_ant","poleas","h0","B","a","Poleas bajas: trabaja la parte alta del pecho|Sube las manos hasta la altura de la barbilla|Codos casi estirados y fijos","Usar los hombros encogiéndolos",2.5);
/* ---- Hombro ---- */
X("press_militar","Press militar con barra de pie","empuje_v","hombro_ant","triceps hombro_lat","barra rack","h2 l1 m1","C","f","Glúteos y abdomen apretados: sin arquear la espalda|La cabeza se retira un poco para que pase la barra|Termina con la barra encima de la cabeza","Echar la cadera adelante y convertirlo en press inclinado",2.5);
X("press_hombro_mancuernas","Press de hombro con mancuernas sentado","empuje_v","hombro_ant","triceps hombro_lat","mancuernas banco_inc","h1 c1","CB","h","Respaldo casi vertical|Baja hasta que las mancuernas queden a la altura de las orejas|Codos ligeramente adelantados","Chocar las mancuernas arriba perdiendo tensión",2);
X("press_hombro_maquina","Press de hombro en máquina","empuje_v","hombro_ant","triceps hombro_lat","press_hombro","h1","CB","h","Asas a la altura de los hombros al empezar|Espalda pegada al respaldo|Recorrido completo","Asiento tan bajo que el hombro sufre abajo",2.5);
X("press_hombro_unilateral","Press de hombro unilateral en máquina","empuje_v","hombro_ant","triceps hombro_lat","press_hombro","h1","CB","h","Un brazo cada vez|Tronco quieto, sin inclinarte|Baja controlando","Compensar con la cadera",2.5);
X("press_smith_hombro","Press de hombro en multipower","empuje_v","hombro_ant","triceps hombro_lat","smith banco_inc","h1","CB","h","Banco vertical colocado para que la barra pase delante de la cara|Baja hasta la barbilla|Codos debajo de las muñecas","Banco mal colocado: la barra roza la cara",2.5);
X("press_landmine","Press landmine","empuje_v","hombro_ant","pecho triceps","barra","h0","CB","h","Barra anclada en una esquina|Empuja hacia arriba y adelante|Muy amable para hombros con molestias","Arquear la espalda",2.5);
X("press_arnold","Press Arnold","empuje_v","hombro_ant","hombro_lat triceps","mancuernas banco_inc","h1","C","h","Empieza con las palmas hacia ti|Gira mientras subes|Movimiento fluido, sin prisas","Peso excesivo que impide girar con control",2);
X("press_kettlebell","Press por encima de la cabeza con kettlebell","empuje_v","hombro_ant","triceps abdomen","kettlebell","h1","C","h","Kettlebell apoyada en el antebrazo|Abdomen y glúteo firmes|Bloquea arriba con el bíceps junto a la oreja","Inclinarse hacia el lado contrario",4);
X("elev_lat_mancuernas","Elevaciones laterales con mancuernas","elev_lateral","hombro_lat","trapecio","mancuernas","h1","B","r","Sube con los codos, no con las manos|Hasta la altura de los hombros|Baja en 2 segundos","Encoger los hombros y balancear el cuerpo",1);
X("elev_lat_polea","Elevación lateral en polea","elev_lateral","hombro_lat","","poleas","h0","SB","r","Polea baja, cable por detrás o por delante del cuerpo|Tensión constante desde abajo|Ligera inclinación lejos de la polea","Tirar del cable con el trapecio",1.25);
X("elev_lat_maquina","Elevaciones laterales en máquina","elev_lateral","hombro_lat","","elev_lat_maq","h0","B","r","Codos apoyados en los cojines|Hombro alineado con el eje de la máquina|Sube hasta la horizontal","Peso que obliga a encogerse",2.5);
X("elev_lat_tumbado","Elevación lateral tumbado de lado","elev_lateral","hombro_lat","","mancuernas banco_inc","h0","S","r","De lado sobre un banco inclinado|Máxima tensión con el brazo abajo, donde más estira|Peso ligero","Usar demasiado peso",1);
X("pajaros","Pájaros con mancuernas","deltoide_post","hombro_post","espalda_media","mancuernas banco_inc","h0","B","r","Pecho apoyado en un banco inclinado|Abre los brazos hacia los lados con codos algo flexionados|Piensa en separar las manos, no en juntar escápulas","Hacer un remo en vez de una apertura",1);
X("face_pull","Face pull","deltoide_post","hombro_post","trapecio espalda_media","poleas","h0","B","a","Polea a la altura de la cara, con cuerda|Tira hacia la frente separando las manos|Pausa de un segundo atrás","Tirar con la espalda echándose hacia atrás",2.5);
X("contractora_inversa","Contractora inversa","deltoide_post","hombro_post","espalda_media","contractora","h0","B","r","Mirando a la máquina, asas a la altura de los hombros|Abre con los brazos casi estirados|Controla la vuelta","Juntar escápulas al final en vez de abrir los brazos",2.5);
X("cruce_inverso","Cruce inverso en poleas","deltoide_post","hombro_post","","poleas","h0","SB","r","Poleas a la altura de los hombros, cables cruzados|Abre los brazos hacia atrás|Brazos casi estirados","Usar impulso",1.25);
/* ---- Espalda ---- */
X("dominadas","Dominadas","tiron_v","dorsal","biceps espalda_media","barra_dominadas","h1 c1","CS","h","Empieza colgado con los brazos estirados|Sube llevando los codos hacia los bolsillos|Barbilla por encima de la barra","Medias repeticiones sin estirar abajo",2.5);
X("dominadas_supinas","Dominadas supinas","tiron_v","dorsal","biceps","barra_dominadas","c1","CS","h","Palmas hacia ti, manos al ancho de hombros|Cuelga del todo abajo|Pecho hacia la barra","Balancear las piernas",2.5);
X("dominadas_asistidas","Dominadas asistidas en máquina","tiron_v","dorsal","biceps espalda_media","asistida","h1","CSB","h","Más contrapeso es más ayuda: quítalo poco a poco|Estira del todo abajo|Codos hacia las costillas","Encoger los hombros arriba",5);
X("jalon","Jalón al pecho","tiron_v","dorsal","biceps espalda_media","jalon","h1","CSB","h","Ajusta el rodillo para que no te levantes|Baja la barra a la parte alta del pecho|Arriba, deja que los brazos se estiren del todo","Echarse muy atrás y convertirlo en remo",2.5);
X("jalon_neutro","Jalón con agarre estrecho neutro","tiron_v","dorsal","biceps","jalon","h0","CSB","h","Asa en V o agarre neutro|Codos pegados al cuerpo|Muy cómodo para hombros sensibles","Tirar con los bíceps sin pensar en los codos",2.5);
X("jalon_unilateral","Jalón unilateral en polea","tiron_v","dorsal","biceps","poleas","h0","CSB","h","De rodillas o sentado bajo la polea alta|Tira llevando el codo a la cadera|Estira del todo arriba","Girar el tronco",1.25);
X("pullover_polea","Pullover en polea alta","pullover","dorsal","triceps","poleas","h1","SB","a","Brazos casi estirados y fijos|Baja la barra hasta los muslos con los dorsales|Arriba, estira notando el dorsal","Doblar los codos y hacerlo con tríceps",2.5);
X("pullover_maquina","Pullover en máquina","pullover","dorsal","","pullover_maq","h1","SB","a","Codos en los cojines|Recorrido completo desde arriba|Controla la vuelta","Arquear la espalda",2.5);
X("pullover_mancuerna","Pullover con mancuerna","pullover","dorsal","pecho triceps","mancuernas banco","h2","S","a","Tumbado en el banco, mancuerna con ambas manos|Baja detrás de la cabeza hasta notar estiramiento|Codos ligeramente flexionados y fijos","Bajar más de lo que el hombro tolera",2);
X("remo_barra","Remo con barra","tiron_h","espalda_media","dorsal biceps lumbar","barra","l2","C","h","Tronco inclinado unos 45°, espalda neutra|Tira hacia el ombligo|Sin incorporarte en cada repetición","Redondear la espalda baja",2.5);
X("remo_mancuerna","Remo con mancuerna a una mano","tiron_h","espalda_media","dorsal biceps","mancuernas banco","","CSB","h","Mano y rodilla apoyadas en el banco|Lleva el codo hacia la cadera|Abajo, deja que el hombro se estire","Girar el tronco para subir más peso",2);
X("remo_apoyado","Remo con mancuernas apoyado en banco inclinado","tiron_h","espalda_media","hombro_post biceps","mancuernas banco_inc","","CB","h","Pecho apoyado en el banco a 30-45°|Codos hacia atrás|Cero carga en la zona lumbar","Despegar el pecho del banco",2);
X("remo_maquina","Remo en máquina con apoyo de pecho","tiron_h","espalda_media","dorsal biceps hombro_post","remo_maq","","CSB","h","Pecho pegado al cojín|Tira con los codos, no con las manos|Estira del todo adelante","Despegar el pecho para usar impulso",2.5);
X("remo_polea_baja","Remo en polea baja sentado","tiron_h","espalda_media","dorsal biceps","poleas","l1","CSB","h","Rodillas algo flexionadas, espalda recta|Tira hacia el ombligo|Deja que los hombros vayan adelante al volver","Balancear el tronco atrás y adelante",2.5);
X("remo_t","Remo en T","tiron_h","espalda_media","dorsal biceps","barra","l1","C","h","Barra anclada en una esquina, asa en V|Pecho alto, espalda neutra|Tira hacia el pecho bajo","Redondear la espalda",2.5);
X("remo_kettlebell","Remo a una mano con kettlebell","tiron_h","espalda_media","dorsal biceps","kettlebell banco","","CB","h","Apoyo firme en el banco|Codo hacia la cadera|Pausa arriba","Girar el tronco",4);
X("remo_invertido","Remo invertido","tiron_h","espalda_media","biceps hombro_post","rack","","CB","a","Barra a la altura de la cintura en el rack o multipower|Cuerpo recto como en una plancha|Pecho a la barra","Dejar caer la cadera",0);
X("remo_unilateral_polea","Remo unilateral en polea","tiron_h","espalda_media","dorsal","poleas","","CSB","h","Polea a media altura|Estira adelante girando un poco el hombro|Tira con el codo pegado","Tirar con el bíceps",1.25);
X("encogimientos_mancuernas","Encogimientos con mancuernas","trapecio","trapecio","","mancuernas","","B","a","Sube los hombros hacia las orejas en línea recta|Pausa de un segundo arriba|Sin girar los hombros","Hacer círculos con los hombros",2);
X("encogimientos_barra","Encogimientos con barra","trapecio","trapecio","","barra","l1","B","a","Barra delante, agarre al ancho de hombros|Sube recto|Pausa arriba","Doblar los codos",2.5);
/* ---- Bíceps ---- */
X("curl_barra","Curl con barra","biceps","biceps","","barra","c1 m1","","h","Codos pegados al cuerpo|Sube sin mover los hombros|Baja del todo, en 2 segundos","Balancear el cuerpo",2.5);
X("curl_barra_z","Curl con barra Z","biceps","biceps","","barra","c1","B","h","Agarre angulado: menos carga en la muñeca|Codos quietos|Recorrido completo","Subir los codos al final",2.5);
X("curl_mancuernas","Curl con mancuernas","biceps","biceps","","mancuernas","","B","h","Gira la palma hacia arriba mientras subes|Un brazo cada vez o a la vez|Baja estirando del todo","Usar impulso de la cadera",1);
X("curl_inclinado","Curl inclinado con mancuernas","biceps","biceps","","mancuernas banco_inc","h1","S","a","Banco a 45-60°, brazos colgando detrás del cuerpo|Gran estiramiento abajo|Peso ligero","Adelantar los codos al subir",1);
X("curl_martillo","Curl martillo","biceps","biceps","","mancuernas","","B","h","Palmas mirándose|Trabaja también el braquial y el antebrazo|Codos fijos","Balancear",1);
X("curl_polea","Curl en polea baja","biceps","biceps","","poleas","","B","a","Tensión constante en todo el recorrido|Codos pegados|Pausa arriba","Echarse atrás",1.25);
X("curl_bayesian","Curl en polea por detrás del cuerpo","biceps","biceps","","poleas","h1","SB","a","De espaldas a la polea, brazo por detrás|Máximo estiramiento del bíceps|Un brazo cada vez","Adelantar el codo",1.25);
X("curl_maquina","Curl de bíceps en máquina","biceps","biceps","","curl_maq","","SB","a","Axila apoyada en el cojín|Eje del codo alineado con la máquina|Estira del todo abajo","Levantar el codo del cojín",2.5);
X("curl_predicador","Curl en banco Scott","biceps","biceps","","banco_scott barra","c1","S","a","Brazos apoyados en el banco|Baja hasta casi estirar, sin rebotar|Sube controlado","Dejar caer el peso abajo: estresa el codo",2.5);
X("curl_arana","Curl araña","biceps","biceps","","mancuernas banco_inc","","B","a","Pecho apoyado en el banco inclinado, brazos colgando|Gran contracción arriba|Sin balanceo posible","Peso excesivo",1);
/* ---- Tríceps ---- */
X("press_frances","Press francés con barra","triceps","triceps","","barra banco","c2","S","h","Baja la barra detrás de la cabeza, no a la frente|Codos apuntando al techo|Sube sin abrirlos","Abrir los codos hacia fuera",2.5);
X("press_frances_mancuernas","Press francés con mancuernas","triceps","triceps","","mancuernas banco","c1","S","h","Palmas mirándose|Baja junto a las orejas|Codos quietos","Mover los hombros",1);
X("ext_triceps_polea_cabeza","Extensión de tríceps en polea por encima de la cabeza","triceps","triceps","","poleas","c1 h1","SB","a","De espaldas a la polea, cuerda detrás de la cabeza|Máximo estiramiento de la cabeza larga|Estira los brazos del todo","Mover los codos adelante y atrás",2.5);
X("ext_triceps_mancuerna_cabeza","Extensión de tríceps con mancuerna por encima de la cabeza","triceps","triceps","","mancuernas","c1 h1","S","a","Sentado con respaldo|Baja detrás de la cabeza|Codos hacia el techo","Arquear la espalda",2);
X("jalon_triceps_cuerda","Extensión de tríceps en polea con cuerda","triceps","triceps","","poleas","","B","a","Codos pegados al cuerpo|Abajo, separa la cuerda|Sube hasta que el antebrazo pase la horizontal","Echar el cuerpo encima del cable",2.5);
X("jalon_triceps_barra","Extensión de tríceps en polea con barra","triceps","triceps","","poleas","c1","B","a","Codos fijos a los lados|Estira del todo abajo|Controla la subida","Separar los codos del cuerpo",2.5);
X("triceps_maquina","Fondos sentado en máquina","triceps","triceps","pecho","triceps_maq","c1","CB","h","Espalda pegada al respaldo|Empuja hasta estirar los brazos|Vuelve controlando","Encoger los hombros",2.5);
X("press_cerrado","Press banca con agarre cerrado","triceps","triceps","pecho hombro_ant","barra banco","h1 c1 m1","C","f","Manos al ancho de hombros, no más juntas|Codos pegados al cuerpo|Barra a la parte baja del pecho","Juntar tanto las manos que sufren las muñecas",2.5);
X("patada_triceps_polea","Patada de tríceps en polea","triceps","triceps","","poleas","","B","a","Tronco inclinado, brazo pegado al cuerpo|Estira el brazo hacia atrás|Pausa al final","Mover el hombro",1.25);
X("fondos_banco","Fondos entre bancos","triceps","triceps","pecho","banco","h2","B","a","Manos en el borde del banco|Baja solo hasta 90° de codo|Hombros lejos de las orejas","Bajar demasiado: sobrecarga el hombro",0);
/* ---- Pierna: rodilla dominante ---- */
X("sentadilla","Sentadilla con barra","sentadilla","cuadriceps","gluteo aductores lumbar","barra rack","r1 l2 k1","CS","f","Barra sobre los trapecios, pies al ancho de hombros|Baja con el pecho alto hasta romper el paralelo si tu movilidad lo permite|Rodillas en la dirección de las puntas de los pies","Redondear la zona lumbar abajo",2.5);
X("sentadilla_frontal","Sentadilla frontal","sentadilla","cuadriceps","gluteo abdomen","barra rack","r1 l1 m1","CS","f","Barra apoyada delante de los hombros, codos altos|Tronco muy vertical|Baja profundo","Dejar caer los codos y la barra",2.5);
X("sentadilla_smith","Sentadilla en multipower","sentadilla","cuadriceps","gluteo","smith","r1 l1","CSB","h","Pies algo adelantados respecto a la barra|Baja controlando hasta donde mantengas la espalda neutra|Empuja con todo el pie","Pies demasiado atrás: carga la rodilla",2.5);
X("hack","Sentadilla hack","sentadilla","cuadriceps","gluteo","hack","r1","CSB","h","Espalda pegada al respaldo|Pies en el centro de la plataforma|Baja todo lo que puedas sin despegar la cadera","Bloquear las rodillas de golpe arriba",5);
X("pendulo","Sentadilla péndulo","sentadilla","cuadriceps","gluteo","pendulo","r1","CSB","h","Hombros bajo los cojines|Baja profundo|Muy buen estímulo de cuádriceps con poca carga en la espalda","Recorrido corto",5);
X("prensa_inclinada","Prensa inclinada","sentadilla","cuadriceps","gluteo aductores","prensa","r1 l1","CB","h","Pies al ancho de hombros en el centro de la plataforma|Baja hasta que la cadera vaya a despegarse del respaldo, no más|No bloquees las rodillas arriba","Bajar tanto que la zona lumbar se despega",5);
X("prensa_horizontal","Prensa horizontal","sentadilla","cuadriceps","gluteo","prensa_h","r1","CB","h","Espalda pegada al respaldo|Recorrido completo y controlado|Rodillas alineadas con los pies","Bloquear las rodillas",5);
X("sentadilla_goblet","Sentadilla goblet","sentadilla","cuadriceps","gluteo abdomen","mancuernas","r1","CSB","h","Mancuerna pegada al pecho|Codos por dentro de las rodillas abajo|Tronco vertical","Talones que se levantan",2);
X("sentadilla_kettlebell","Sentadilla con kettlebell al pecho","sentadilla","cuadriceps","gluteo","kettlebell","r1","CB","h","Kettlebell pegada al pecho|Baja profundo con el pecho alto|Empuja con todo el pie","Inclinar el tronco adelante",4);
X("bulgara","Sentadilla búlgara con mancuernas","zancada","cuadriceps","gluteo aductores","mancuernas banco","r1 k1","CS","h","Pie trasero sobre el banco|Más inclinación del tronco, más glúteo; más vertical, más cuádriceps|Baja hasta que la rodilla trasera casi toque el suelo","Pie delantero demasiado cerca del banco",2);
X("bulgara_smith","Sentadilla búlgara en multipower","zancada","cuadriceps","gluteo","smith banco","r1 k1","CSB","h","La barra guía y da estabilidad|Pie trasero en el banco|Baja vertical","Colocación inestable del pie trasero",2.5);
X("zancada_atras","Zancada hacia atrás con mancuernas","zancada","cuadriceps","gluteo","mancuernas","","CB","h","Paso largo hacia atrás|La rodilla delantera sufre menos que en la zancada adelante|Empuja con el talón delantero","Paso demasiado corto",2);
X("zancada_caminando","Zancadas caminando","zancada","cuadriceps","gluteo","mancuernas","r1","C","h","Pasos largos y controlados|Tronco recto|Alterna piernas","Pasos cortos que cargan la rodilla",2);
X("step_up","Subida al banco con mancuernas","zancada","cuadriceps","gluteo","mancuernas banco","r1","CB","h","Banco a la altura de la rodilla|Sube empujando con la pierna de arriba|Baja despacio","Impulsarse con la pierna de abajo",2);
X("zancadas_corporal","Zancadas sin peso","zancada","cuadriceps","gluteo","","r1","B","a","Paso largo|Rodilla trasera cerca del suelo|Tronco recto","Rodilla delantera hacia dentro",0);
X("ext_cuadriceps","Extensión de cuádriceps","ext_rodilla","cuadriceps","","ext_cuad","r1","SB","a","Rodilla alineada con el eje de la máquina|Respaldo algo reclinado: más estiramiento del recto femoral|Pausa arriba, baja en 2 segundos","Golpear el peso abajo",2.5);
X("ext_cuadriceps_unilateral","Extensión de cuádriceps a una pierna","ext_rodilla","cuadriceps","","ext_cuad","r1","SB","a","Una pierna cada vez: corrige diferencias|Recorrido completo|Pausa arriba","Levantar la cadera del asiento",2.5);
/* ---- Pierna: cadera dominante ---- */
X("peso_muerto_rumano","Peso muerto rumano con barra","bisagra","isquios","gluteo lumbar","barra","l1","CS","h","Rodillas algo flexionadas y fijas|Lleva la cadera atrás deslizando la barra por los muslos|Baja hasta notar estiramiento en los isquios con la espalda recta","Redondear la espalda para bajar más",2.5);
X("peso_muerto_rumano_mancuernas","Peso muerto rumano con mancuernas","bisagra","isquios","gluteo lumbar","mancuernas","l1","CSB","h","Mancuernas pegadas a las piernas|Cadera atrás, espalda neutra|Sube apretando el glúteo","Doblar mucho las rodillas: se convierte en sentadilla",2);
X("peso_muerto","Peso muerto convencional","bisagra","gluteo","isquios lumbar espalda_media cuadriceps","barra","l2 r1","C","f","Barra sobre el medio del pie|Espalda neutra y dorsales tensos antes de tirar|Empuja el suelo y lleva la cadera adelante al final","Tirar con la espalda redondeada",5);
X("peso_muerto_hex","Peso muerto con barra hexagonal","bisagra","gluteo","cuadriceps isquios","trap","l1 r1","CB","f","Dentro de la barra, asas a los lados|Más vertical y más amable con la espalda|Empuja el suelo","Subir la cadera antes que los hombros",5);
X("peso_muerto_kettlebell","Peso muerto con kettlebell","bisagra","gluteo","isquios","kettlebell","l1","CB","h","Kettlebell entre los pies|Cadera atrás, espalda neutra|Aprieta glúteo arriba","Redondear la espalda",4);
X("rumano_unilateral","Peso muerto rumano a una pierna","bisagra","isquios","gluteo","mancuernas","","S","h","Mancuerna en la mano contraria a la pierna de apoyo|Cadera cuadrada al suelo|Baja hasta notar estiramiento","Abrir la cadera girando",2);
X("hiperextension","Hiperextensión a 45°","bisagra","gluteo","isquios lumbar","banco_45","l1","SB","a","Cadera justo por encima del cojín|Baja con la espalda neutra|Sube apretando glúteo, sin pasar de la línea del cuerpo","Hiperextender la zona lumbar arriba",2.5);
X("pull_through","Pull through en polea","bisagra","gluteo","isquios","poleas","","B","a","De espaldas a la polea baja, cuerda entre las piernas|Cadera atrás|Sube llevando la cadera adelante","Tirar con los brazos",2.5);
X("swing_kettlebell","Swing con kettlebell","bisagra","gluteo","isquios abdomen","kettlebell","l1","C","r","Es una bisagra explosiva, no una sentadilla|La cadera impulsa; los brazos solo guían|Aprieta glúteo y abdomen arriba","Levantar la kettlebell con los hombros",4);
X("curl_femoral_sentado","Curl femoral sentado","flex_rodilla","isquios","gemelo","curl_fem_sentado","","SB","a","Rodilla alineada con el eje|Sentado, el isquio trabaja más estirado: es la mejor opción|Pausa con las piernas dobladas","Despegar la cadera del asiento",2.5);
X("curl_femoral_tumbado","Curl femoral tumbado","flex_rodilla","isquios","gemelo","curl_fem_tumbado","","B","a","Cadera pegada al banco|Sube hasta casi tocar el glúteo|Baja en 2 segundos","Levantar la cadera",2.5);
X("curl_femoral_polea","Curl femoral de pie en polea","flex_rodilla","isquios","","poleas","","B","a","Tobillera en la polea baja|Una pierna cada vez|Cadera quieta","Mover la cadera",1.25);
X("curl_nordico","Curl nórdico","flex_rodilla","isquios","","","r2","S","r","Rodillas sobre una esterilla, tobillos sujetos|Baja lo más lento posible|Ayúdate con las manos para subir","Doblar la cadera",0);
X("hip_thrust","Hip thrust con barra","gluteo","gluteo","isquios","barra banco","k1","CB","h","Espalda alta en el borde del banco|Pies a la distancia que deje la tibia vertical arriba|Mentón al pecho y aprieta glúteo arriba","Arquear la zona lumbar en vez de extender la cadera",5);
X("hip_thrust_maquina","Hip thrust en máquina","gluteo","gluteo","isquios","hip_thrust_maq","","CB","h","Ajusta el cinturón sobre la cadera|Pausa arriba|Recorrido completo","Hiperextender la espalda",5);
X("hip_thrust_smith","Hip thrust en multipower","gluteo","gluteo","isquios","smith banco","k1","CB","h","Barra guiada: más estable|Espalda alta en el banco|Aprieta arriba","Pies mal colocados",5);
X("puente_gluteo","Puente de glúteo","gluteo","gluteo","isquios","","","B","r","Tumbado, pies cerca del glúteo|Sube la cadera apretando glúteo|Pausa arriba","Arquear la espalda",0);
X("abductora","Máquina de abductores","gluteo","gluteo","","abductor","","B","r","Inclinarte un poco adelante carga más el glúteo|Abre con control|Pausa al abrir","Dejar que el peso cierre de golpe",2.5);
X("patada_gluteo_polea","Patada de glúteo en polea","gluteo","gluteo","","poleas","","B","a","Tobillera en la polea baja|Lleva la pierna atrás sin arquear la espalda|Pausa arriba","Mover la zona lumbar",1.25);
X("aductora","Máquina de aductores","aductor","aductores","","aductor","k1","SB","a","Abre hasta notar estiramiento|Cierra con control|Pausa al cerrar","Abrir más de lo que tolera la cadera",2.5);
X("gemelo_pie","Gemelo de pie en máquina","gemelo","gemelo","","gemelo_pie","","SB","a","Talones bajan del todo: el estiramiento es clave|Pausa de 1-2 segundos abajo|Sube de puntillas del todo","Rebotar en el fondo",5);
X("gemelo_prensa","Gemelo en prensa","gemelo","gemelo","","prensa","","SB","a","Solo la punta del pie en la plataforma|Rodillas casi estiradas|Pausa con el talón abajo","Doblar las rodillas",5);
X("gemelo_sentado","Gemelo sentado","gemelo","gemelo","","gemelo_sentado","","B","a","Trabaja más el sóleo|Recorrido completo|Pausa abajo","Rebotar",5);
X("gemelo_smith","Gemelo de pie en multipower","gemelo","gemelo","","smith","","SB","a","Puntas sobre un disco o escalón|Baja del todo|Pausa abajo","Doblar rodillas",5);
X("gemelo_mancuerna","Gemelo a una pierna con mancuerna","gemelo","gemelo","","mancuernas","","SB","a","De pie en un escalón, mancuerna en la mano del mismo lado|Baja del todo|Una pierna cada vez","Rebotar",2);
/* ---- Core ---- */
X("crunch_polea","Crunch en polea alta","core","abdomen","","poleas","","SB","a","De rodillas, cuerda junto a la cabeza|Enrolla la columna llevando los codos a los muslos|La cadera no se mueve","Sentarse sobre los talones",2.5);
X("elev_piernas_colgado","Elevación de piernas colgado","core","abdomen","","barra_dominadas","h1","S","a","Cuelga sin balanceo|Sube las rodillas enrollando la pelvis|Baja lento","Balancearse",0);
X("elev_piernas_paralelas","Elevación de rodillas en paralelas","core","abdomen","","paralelas","","B","a","Antebrazos apoyados|Rodillas al pecho|Baja controlando","Balancear",0);
X("rueda_abdominal","Rueda abdominal","core","abdomen","","","l1","S","a","De rodillas|Avanza solo hasta donde mantengas la espalda neutra|Vuelve con el abdomen","Hundir la zona lumbar",0);
X("plancha","Plancha","core","abdomen","","","","B","s","Codos debajo de los hombros|Glúteo y abdomen apretados|Respira normal","Cadera caída o demasiado alta",0);
X("pallof","Press Pallof","core","abdomen","","poleas","","B","a","De lado a la polea a la altura del pecho|Empuja las manos al frente sin dejarte girar|Pausa con los brazos estirados","Rotar el tronco",1.25);
X("dead_bug","Dead bug","core","abdomen","","","","B","a","Tumbado boca arriba, zona lumbar pegada al suelo|Estira brazo y pierna contrarios|Lento y controlado","Despegar la espalda del suelo",0);
X("plancha_carga_lateral","Paseo o sostén con carga lateral","core","abdomen","trapecio","kettlebell","","B","s","Peso en una sola mano|Tronco recto, sin inclinarte|Aguanta respirando","Inclinarse hacia el peso",4);
const EXM=Object.fromEntries(EX.map(e=>[e.id,e]));
